import type { Finding, JobResult, OpportunityRecord } from "./types";

export const findings: Finding[] = [
  {
    level: "High",
    title: "The traits are asserted, not demonstrated",
    quote: "Known for reliability, discipline, and strong leadership.",
    why: "“Known for” asks the reader to take your word for it. A civilian hiring reader treats unverifiable trait claims as filler and skips past them — the sentence spends prime summary space proving nothing.",
    task: "Replace this sentence with one specific, verifiable outcome your leadership produced. Keep the traits only if an example on the page backs them.",
  },
  {
    level: "High",
    title: "“Operations” carries no civilian meaning here",
    quote: "Planned and carried out operations and training, consistently meeting deadlines and standards.",
    why: "The reader cannot see what was planned, for how many people, under what constraints, or what meeting the standard looked like. As written, this summary line could describe almost any job at any level.",
    task: "Choose one training event or operation you planned. Name what you organized, for how many people, and one observable result — without disclosing sensitive details.",
  },
  {
    level: "Medium",
    title: "The recognition is real but unnamed",
    quote: "Completed an overseas deployment and earned recognition for leadership and dependability.",
    why: "Nowhere on the page does the résumé say what the recognition was — no award name, level, or reason appears. A civilian reader discounts an unnamed “recognition” as self-description; a specific award or a concrete reason would carry the weight this vague noun cannot.",
    task: "Name the specific recognition — the award, its level, or who gave it — and add one clause, in civilian terms, for what it was awarded. If it cannot be substantiated, cut the clause.",
  },
];

export const searchResults: JobResult[] = [
  {
    id: "sample-aeronorth-technical-operations-manager",
    source: "sample",
    title: "Technical Operations Manager",
    company: "AeroNorth Systems",
    place: "Jacksonville, FL · Hybrid",
    pay: "$94,000–$118,000",
    age: "Posted 3 hours ago",
    type: "Full-time",
    apply: "Quick apply",
    fit: "88% fit",
  },
  {
    id: "sample-harbor-maintenance-planning-manager",
    source: "sample",
    title: "Maintenance Planning Manager",
    company: "Harbor Aviation",
    place: "Savannah, GA · On-site",
    pay: "$86,000–$104,000",
    age: "Posted 1 day ago",
    type: "Full-time",
    apply: "Company site",
    fit: "82% fit",
  },
  {
    id: "sample-atlas-field-service-operations-lead",
    source: "sample",
    title: "Field Service Operations Lead",
    company: "Atlas Flight Systems",
    place: "Remote · Southeast",
    pay: "$88,000–$112,000",
    age: "Posted 2 days ago",
    type: "Full-time",
    apply: "Quick apply",
    fit: "79% fit",
  },
];

export const opportunityRecords: OpportunityRecord[] = [
  {
    id: "demo-aeronorth-technical-operations-manager",
    company: "AeroNorth Systems",
    role: "Technical Operations Manager",
    location: "Jacksonville, FL · Hybrid",
    source: "demo",
    sourceId: "sample:sample-aeronorth-technical-operations-manager",
    status: "Interview",
    createdAt: "2026-07-10T14:00:00.000Z",
    statusChangedAt: "2026-07-18T14:00:00.000Z",
    appliedDate: "2026-07-10",
    materials: { resume: "Resume v3", coverLetter: "Cover letter sent" },
    contact: { name: "Jordan Lee", relationship: "Operations Director" },
    nextAction: {
      kind: "practice-interview",
      label: "Interview Prep",
      detail: "Company brief ready",
      dueDate: "2026-07-19",
    },
  },
  {
    id: "demo-harbor-maintenance-planning-lead",
    company: "Harbor Aviation",
    role: "Maintenance Planning Lead",
    location: "Savannah, GA · On-site",
    source: "demo",
    status: "Applied",
    createdAt: "2026-07-15T14:00:00.000Z",
    statusChangedAt: "2026-07-15T14:00:00.000Z",
    appliedDate: "2026-07-15",
    materials: { resume: "Resume v2", coverLetter: "Cover letter sent" },
    nextAction: {
      kind: "follow-up",
      label: "Follow up call",
      detail: "No response since applying",
      dueDate: "2026-07-21",
    },
  },
  {
    id: "demo-northgate-operations-supervisor",
    company: "Northgate Logistics",
    role: "Operations Supervisor",
    source: "demo",
    status: "Applied",
    createdAt: "2026-07-17T14:00:00.000Z",
    statusChangedAt: "2026-07-17T14:00:00.000Z",
    appliedDate: "2026-07-17",
    materials: { resume: "Resume v2", coverLetter: "Cover letter sent" },
    contact: { name: "Ms. Alvarez", relationship: "Hiring Manager" },
    nextAction: {
      kind: "follow-up",
      label: "Follow up call",
      detail: "No response yet",
      dueDate: "2026-07-24",
    },
  },
  {
    id: "demo-meridian-cybersecurity-operations-analyst",
    company: "Meridian Grid",
    role: "Cybersecurity Operations Analyst",
    source: "demo",
    status: "Preparing",
    createdAt: "2026-07-15T14:00:00.000Z",
    statusChangedAt: "2026-07-18T14:00:00.000Z",
    materials: { resume: "Resume gap review", coverLetter: "Cover letter pending" },
    contact: { name: "Priya Shah", relationship: "Security Manager" },
    nextAction: {
      kind: "review-resume",
      label: "Tailor resume",
      detail: "Address SIEM qualification gap first",
      dueDate: "2026-07-22",
    },
  },
];