import type { ApplicationRow, Finding, JobResult } from "./types";

export const findings: Finding[] = [
  {
    level: "High",
    title: "The traits are asserted, not demonstrated",
    quote: "Known for reliability, discipline, and strong leadership.",
    why: "“Known for” asks the reader to take your word for it. A civilian hiring reader treats unverifiable trait claims as filler and skips past them — the sentence spends prime summary space proving nothing.",
    task: "Replace this sentence with one specific, verifiable outcome your leadership produced. Keep the traits only if an example on the page backs them.",
  },
  {
    level: "High",
    title: "“Operations” carries no civilian meaning here",
    quote: "Planned and carried out operations and training, consistently meeting deadlines and standards.",
    why: "The reader cannot see what was planned, for how many people, under what constraints, or what meeting the standard looked like. As written, the bullet could describe almost any job at any level.",
    task: "Choose one training event or operation you planned. Name what you organized, for how many people, and one observable result — without disclosing sensitive details.",
  },
  {
    level: "Medium",
    title: "The recognition is real but unnamed",
    quote: "Completed an overseas deployment and earned recognition for leadership and dependability.",
    why: "Your awards section names a Navy and Marine Corps Achievement Medal, but this bullet hides it behind the vague word “recognition” — which reads weaker than the specific award you actually earned.",
    task: "Name the award here and add one clause, in civilian terms, saying what it was awarded for.",
  },
];

export const searchResults: JobResult[] = [
  {
    title: "Technical Operations Manager",
    company: "AeroNorth Systems",
    place: "Jacksonville, FL · Hybrid",
    pay: "$94,000–$118,000",
    age: "Posted 3 hours ago",
    type: "Full-time",
    apply: "Quick apply",
    fit: "88% fit",
  },
  {
    title: "Maintenance Planning Manager",
    company: "Harbor Aviation",
    place: "Savannah, GA · On-site",
    pay: "$86,000–$104,000",
    age: "Posted 1 day ago",
    type: "Full-time",
    apply: "Company site",
    fit: "82% fit",
  },
  {
    title: "Field Service Operations Lead",
    company: "Atlas Flight Systems",
    place: "Remote · Southeast",
    pay: "$88,000–$112,000",
    age: "Posted 2 days ago",
    type: "Full-time",
    apply: "Quick apply",
    fit: "79% fit",
  },
];

export const applicationRows: ApplicationRow[] = [
  {
    role: "Technical Operations Manager",
    roleDetail: "AeroNorth Systems · Applied Jul 10",
    stage: "Interview 1",
    stageClass: "interview-stage",
    materials: "Resume v3",
    materialsDetail: "Cover letter sent",
    contact: "Jordan Lee",
    contactDetail: "Operations Director",
    nextAction: "Interview Prep",
    nextActionDetail: "Company brief ready",
    nextActionView: "interview",
    due: "Jul 19",
  },
  {
    role: "Maintenance Planning Lead",
    roleDetail: "Harbor Aviation · Applied Jul 15",
    stage: "Applied",
    stageClass: "applied-stage",
    materials: "Resume v2",
    materialsDetail: "Cover letter sent",
    contact: "Recruiting team",
    contactDetail: "No direct contact yet",
    nextAction: "Follow up call",
    nextActionDetail: "No response since applying",
    due: "Jul 21",
  },
  {
    role: "Cybersecurity Operations Analyst",
    roleDetail: "Meridian Grid · Saved Jul 15",
    stage: "Preparing",
    stageClass: "saved-stage",
    materials: "Resume gap review",
    materialsDetail: "Cover letter pending",
    contact: "Priya Shah",
    contactDetail: "Security Manager",
    nextAction: "Tailor resume",
    nextActionDetail: "Address SIEM qualification gap first",
    nextActionView: "resume",
    due: "Jul 22",
  },
];
